site_name: Real-Time Cyber Anomaly Detection
site_url: https://francescacraievich.github.io/real-time-cyber-anomaly-detection/
site_author: Francesca Craievich
site_description: Real-time network anomaly detection system

repo_name: real-time-cyber-anomaly-detection
repo_url: https://github.com/francescacraievich/real-time-cyber-anomaly-detection

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - Overview: overview.md
  - Kick Off: kick_off.md
  - Data Collection: data_collection.md

  - Data Engineering:
      - Guide for Data Processing Classes: data_engineering_docs/Guide for Data Processing Classes.md
      - Feature Engineering: data_engineering_docs/feature_engineering.md
      - Data Engineer Logs: data_engineering_docs/data_engineer_logs.md
      - Log Formatting: data_engineering_docs/log_formatting.md
